### ISSUE TITLE
Create stage instructions missing stage_name value

### ISSUE THREAD

**Issue by paveljasek** [google/crmint#134]
When deploying CRMint using the [Quickstart](https://google.github.io/crmint/docs/quickstart/), one of the steps proposes using
```
crmint stages create
```
This creates a blank directory
These instructions are missing --stage_name=PROJECT_ID with specific project name as this stage name 
I expect the instruction should be 
```
crmint stages create --stage_name=PROJECT_ID
```

**Comment by Slony** [comment]
Hey @paveljasek, thank you for your feedback and suggestion.

Initially, the deployment scripts were designed to operate in the context of a selected Google Cloud project. But it those cases when a user opens Cloud Shell in a separate window, the Cloud project is not being selected by default. That's why we've added the following command to the [Deploy CRMint on Google Cloud Platform](https://github.com/google/crmint/wiki/Deploy-CRMint-on-Google-Cloud-Platform) guide:

```bash
# Double check if a Cloud Project is selected.
[ "$GOOGLE_CLOUD_PROJECT" == "" ] && echo -n 'Input a Cloud Project ID: ' && read project_id && gcloud config set project "$project_id"
```

And of course, adding a `--stage_name=PROJECT_ID` flag to the commands listed below works as well:

```bash
crmint cloud setup --stage_name=PROJECT_ID
crmint cloud deploy --stage_name=PROJECT_ID
```

In the future version we will address the issue with a Cloud project not being selected during the CRMint deployment.

Please let me know if you have any questions.

Cheers!
