### ISSUE TITLE
Data to CSV, execution failed due to file size

### ISSUE THREAD

**Issue by tushspeed** [google/crmint#150]
the data to csv job is failing due to size limits on GBQ for single file exports, 

```Execution failed: WorkerException: Table gs://noon-crm.appspot.com/dataimport.csv too large to be exported to a single file. Specify a uri including a * to shard export. See 'Exporting data into one or more files' in https://cloud.google.com/bigquery/docs/exporting-data.```

Any suggestion to either reduce the size or shard the file for next stages?

**Comment by Slony** [comment]
Hi @tushspeed, thank you for raising this issue.

Actually, you can specify the destination CSV or JSON file URI with a `*` wildcard in the job for `BQToStorageExporter` worker class like this:

```
gs://noon-crm.appspot.com/dataimport*
```

This should allow you to export larger files from BigQuery to Cloud Storage.

At the same time, if you're exporting the data for further upload into Google Analytics [Data Import](https://support.google.com/analytics/topic/6065609?hl=en&ref_topic=1727148) dataset in [Query Time import](https://support.google.com/analytics/answer/6071511?hl=en&ref_topic=6064627) mode, you probably have to consider reducing the data size in order to stay within 1GB quota applied for the total amount of uploaded files. Please refer to Upload Limits section of [Limits of Data Import](https://support.google.com/analytics/answer/6016094?hl=en&ref_topic=6065475).

Speaking of reducing the file size in case of uploading the users' data to Google Analytics, I can suggest a couple of things:

 **Using shorter User IDs**, e.g. using simple integer numbers instead of [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier) or [SHAs](https://en.wikipedia.org/wiki/Secure_Hash_Algorithms).

This might require quite a few changes on your website and in your back-end systems.

**Packing values of multiple custom dimension** into one value for just one custom dimension. For example, if you have three RFM dimensions with five possible segments from1 to 5 in each dimension, then you can pack the RFM segments in a single dimension using something as simple as this:

```
PackedValue = 25 * (R - 1) + 5 * (F - 1) + (M - 1)
```

This will allow to save from 2 to 4 bytes in each line of the CSV file — no so few if you have tens of millions of lines.

This might require changing your CRMint pipeline(s) accordingly.

Please let me know if you have any questions.

**Comment by tushspeed** [comment]
hi @Slony I got the multiple exports to GCS, however `Data to GA QT` is giving error as below: 
```Job: Data to GA QT, Worker Class: GADataImporter
Unexpected error: NotFoundError: Expect status [200] from Google Storage. But got status 404.
Path: '/noon-crm.appspot.com/dataimport%2A'.
Request headers: None.
Response headers: {'content-length': '194', 'expires': 'Sun, 26 Jan 2020 10:07:59 GMT', 'x-guploader-uploadid': 'AEnB2UotuuHD0nHWOTd7aj-DB3IOS_Ga-m596XXvol3Lbpe0IxiOFqGCJsAnE2C780y6NmU6HBHbe_U5_p7JqGM-EQQLj2nM4bRXVOKtFwQfPmZxpdCw3fA', 'cache-control': 'private, max-age=0', 'date': 'Sun, 26 Jan 2020 10:07:59 GMT', 'content-type': 'application/xml; charset=UTF-8'}.
Body: ''.
Extra info: None.```

**Comment by Slony** [comment]
hi @tushspeed In params of `GADataImporter` worker that is used for `Data to GA QT` job you have to specify one GCS file without wildcards. In case you export data from BigQuery to several files in GCS, you might try using several jobs similar to `Data to GA QT` — one job per file.

Please let me know if it does make sense to you.

**Comment by Slony** [comment]
@tushspeed I'm closing this issue, please feel free to re-open it.
