### ISSUE TITLE
GAAudiencesUpdater

### ISSUE THREAD

**Issue by garanj** [google/crmint#42]
Is there somewhere I can find more about the format of "GA audience JSON template"

**Comment by Slony** [comment]
__GAAudiencesUpdater__ uses Google Analytics Management API to create audiences in Google Analytics and update these audiences.

Parameters are:

* Google Analytics property ID,
* BigQuery project ID,
* BigQuery dataset ID,
* BigQuery table ID, and
* Google Analytics audience JSON template.

BigQuery project ID, dataset ID, and table ID are user to identify a table where the worker will get the input data from. For every row in the table, __GAAudiencesUpdater__ will create (or update) an audience list using JSON as a template and row fields as values for placeholders in the template.

Here's the basic Google Analytics JSON template example:

```
{
  "audienceType": "STATE_BASED",
  "linkedAdAccounts": [
    {
      "linkedAccountId": "{% AW_ACCOUNT_ID %}",
      "type": "ADWORDS_LINKS"
    }
  ],
  "linkedViews": [
    {% GA_VIEW_ID %}
  ],
  "name": "CRMint Tier GA %(tier)i",
  "stateBasedAudienceDefinition": {
    "includeConditions": {
      "daysToLookBack": 7,
      "segment": "users::condition::ga:dimension{% CD_TIER %}=@%(code)s",
      "isSmartList": false,
      "membershipDurationDays": %(duration)i
    },
    "excludeConditions": {
      "segment": "users::condition::ga:dimension{% CD_TIER %}==dur93j#%(tier)ihg@2d6",
      "exclusionDuration": "TEMPORARY"
    }
  }
}
```

In this example, __GAAudiencesUpdater__ will look for or create an audience named `CRMint Tier GA %(tier)i` where `%(tier)i` is a placeholder that will be replaced with an integer value of `tier` column in the BigQuery table. `%(duration)i` placeholder will be replaced with an integer value of `duration` column. `%(code)s` placeholder will be replaced with string value from `code` column. You can customise JSON templates according to your own setting.

Please, note that `{% AW_ACCOUNT_ID %}`, `{% GA_VIEW_ID %}` and `{% CD_TIER %}` placeholders will be replaced with values of corresponding variables defined at pipeline or at global level.

To create Google Analytics audiences shared with MCC instead of simple AdWords account, you have to replace `ADWORDS_LINKS` with `MCC_LINKS` in `linkedAdAccounts.type`:

```
{
  "audienceType": "STATE_BASED",
  "linkedAdAccounts": [
    {
      "linkedAccountId": "{% AW_ACCOUNT_ID %}",
      "type": "MCC_LINKS"
    }
  ],
  "linkedViews": [
    {% GA_VIEW_ID %}
  ],
  "name": "CRMint Tier GA %(tier)i",
  "stateBasedAudienceDefinition": {
    "includeConditions": {
      "daysToLookBack": 7,
      "segment": "users::condition::ga:dimension{% CD_TIER %}=@%(code)s",
      "isSmartList": false,
      "membershipDurationDays": %(duration)i
    },
    "excludeConditions": {
      "segment": "users::condition::ga:dimension{% CD_TIER %}==dur93j#%(tier)ihg@2d6",
      "exclusionDuration": "TEMPORARY"
    }
  }
}
```

If you need to create/update Google Analytics audiences _without exclude conditions_, then you have to:

1. change `audienceType` from `STATE_BASED` to `SIMPLE`,
2. omit `excludeConditions` section,
3. change `stateBasedAudienceDefinition` section name to `audienceDefinition`,

like this:

```
{
  "audienceType": "SIMPLE",
  "linkedAdAccounts": [
    {
      "linkedAccountId": "{% AW_ACCOUNT_ID %}",
      "type": "ADWORDS_LINKS"
    }
  ],
  "linkedViews": [
    {% GA_VIEW_ID %}
  ],
  "name": "CRMint Tier GA %(tier)i",
  "audienceDefinition": {
    "includeConditions": {
      "daysToLookBack": 7,
      "segment": "users::condition::ga:dimension{% CD_TIER %}=@%(code)s",
      "isSmartList": false,
      "membershipDurationDays": %(duration)i
    }
  }
}
```

Please, see [JSON template for an Analytics remarketing audience](https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/remarketingAudience#resource) for more details on how to represent GA audience using JSON format.

**Comment by garanj** [comment]
Very helpful - I am proposing:
- I'll add a link to the worker spec page
- A guide (probably based entirely off this post!) for more in-depth usage

**Comment by PA-Mousset** [comment]
Very hard to work with CRMint as there is a lack of documentation. For example, `{% AW_ACCOUNT_ID %}`, what does this stands for? I guess AW stands for Amazon, but what about if I am using GCP?

**Comment by Slony** [comment]
`AW_ACCOUNT_ID` assumed to be a CRMint's pipeline (or global) [variable](https://google.github.io/crmint/docs/guides/variables.html) that has a value equal to [customer ID](https://support.google.com/google-ads/answer/1704344) of the Google Ads account linked to the Google Analytics audiences that `GAAudiencesUpdater` creates and manages.
